services:
  iris:
    build:
      context: .
    command: --check-caps false
    ports:
      - 52773:52773
      - 8501:8501
    volumes:
      - ./web:/opt/coffee/csp
      - ./tests:/opt/coffee/tests
      - ./:/irisdev/app
